# Generated by Django 5.1.4 on 2025-02-22 10:03

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('project', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('audio_file', models.FileField(upload_to='uploads/')),
                ('transcription_file', models.FileField(upload_to='uploads/')),
                ('embeddings', pgvector.django.vector.VectorField(dimensions=1536)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
