# Generated by Django 5.1.4 on 2025-05-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('transcription', '0002_alter_meeting_embeddings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='team',
        ),
        migrations.AddField(
            model_name='meeting',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('team', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('team_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.team')),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='transcription.project'),
        ),
    ]
