# Generated by Django 5.1.4 on 2025-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_remove_meeting_team_meeting_timestamp_meeting_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
