# Generated by Django 5.1.4 on 2025-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconnection',
            name='flow',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
