# Generated by Django 5.1.4 on 2025-06-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0002_calendarconnection_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarconnection',
            name='microsoft_token',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarconnection',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='calendarconnection',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
